#make /home/cmp408/tools/arm-bcm2708/arm-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc DisplayApp.c
all: DisplayApp.c
	/home/cmp408/tools/arm-bcm2708/arm-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc -g -Wall -o DisplayApp DisplayApp.c

clean: 
	$(RM) DisplayApp